spring.application.name=HealthRemainder

# =======================
# MYSQL from Railway
# =======================
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Auto-select MySQL dialect (recommended)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.open-in-view=false

# =======================
# REQUIRED FOR RENDER
# =======================
server.port=${PORT:8080}
